# Generated by Django 4.1.7 on 2023-04-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='user',
        ),
    ]
