# Generated by Django 4.1.7 on 2023-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_addbook_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddBook',
        ),
    ]
