# Generated by Django 4.1.7 on 2023-04-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_addbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddBook',
        ),
    ]
