# Generated by Django 4.1.7 on 2023-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_book1_issuebook_bookid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='user',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='studentuser',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
