# Generated by Django 4.1.7 on 2023-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_issuebook_user_issuebook_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='status',
            field=models.CharField(default='Non issued', max_length=20),
        ),
    ]
