# Generated by Django 4.1.7 on 2023-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_addbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='bookname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='stuname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
