# Generated by Django 4.1.7 on 2023-04-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_issuebook_bookname_issuebook_stuname'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
