# Generated by Django 4.1.7 on 2023-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_issuebook_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookhistory',
            fields=[
                ('bookid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('deletedate', models.DateField(auto_now=True)),
                ('deletetime', models.TimeField(auto_now=True)),
            ],
        ),
    ]
