# Generated by Django 4.1.7 on 2023-04-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_bookhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnBook',
        ),
    ]
