# Generated by Django 4.1.7 on 2023-04-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_addbook_bookpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='bookpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
