# Generated by Django 4.1.7 on 2023-04-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_issuebook_bookpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='bookpic',
        ),
    ]
