# Generated by Django 4.1.7 on 2023-04-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_addbook_bookpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='bookpic',
        ),
    ]
