# Generated by Django 4.1.7 on 2023-03-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
