# Generated by Django 4.1.7 on 2023-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
