# Generated by Django 4.1.7 on 2023-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='lid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
